name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-amd64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - uses: actions/checkout@v3
    - name: Testing on amd64
      run: go test -v ./...
