name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io qemu binfmt-support qemu-user-static
    - name: Testing on amd64
      run: |
        sudo docker docker pull --platform=linux/amd64
        sudo run --rm --platform=linux/amd64 hello-world
    - name: Testing on arm64
      run: |
        sudo docker docker pull --platform=linux/arm64
        sudo run --rm --platform=linux/arm64 hello-world
