name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu binfmt-support qemu-user-static
    - name: Testing on amd64
      run: |
        docker pull --platform=linux/amd64 golang
        docker run --rm --platform=linux/amd64 -w /usr/src/ --mount type=bind,source="${GITHUB_WORKSPACE}",target=/usr/src/ golang go test -v
    - name: Testing on 386
      run: |
        docker pull --platform=linux/386 golang
        docker run --rm --platform=linux/386 -w /usr/src/ --mount type=bind,source="${GITHUB_WORKSPACE}",target=/usr/src/ golang go test -v
    - name: Testing on arm64
      run: |
        docker pull --platform=linux/arm64 golang
        docker run --rm --platform=linux/arm64 -w /usr/src/ --mount type=bind,source="${GITHUB_WORKSPACE}",target=/usr/src/ golang go test -v
    - name: Testing on arm
      run: |
        docker pull --platform=linux/arm/v7 golang
        docker run --rm --platform=linux/arm/v7 -w /usr/src/ --mount type=bind,source="${GITHUB_WORKSPACE}",target=/usr/src/ golang go test -v
