name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Instal packages
      run: sudo apt-get install -y docker.io qemu binfmt-support qemu-user-static
    - uses: actions/checkout@v3
    - name: Testing on amd64
    - run: sudo docker docker pull --platform=linux/amd64
    - run: sudo run --rm --platform=linux/amd64 hello-world
    - name: Testing on arm64
    - run: sudo docker docker pull --platform=linux/arm64
    - run: sudo run --rm --platform=linux/arm64 hello-world
